Document: grub2-once
Title: Debian grub2-once Manual
Author: <insert document author here>
Abstract: This manual describes what grub2-once is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/grub2-once/grub2-once.sgml.gz

Format: postscript
Files: /usr/share/doc/grub2-once/grub2-once.ps.gz

Format: text
Files: /usr/share/doc/grub2-once/grub2-once.text.gz

Format: HTML
Index: /usr/share/doc/grub2-once/html/index.html
Files: /usr/share/doc/grub2-once/html/*.html
